# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e596d90aafee7d14e295eff11ffc9785ad4dfffc79c91bf5c2f0cf690119ebd5f5c288f217ecbb17899e816383a3a76894150f254d4eb6f47206bdfd74508b

test:
  secret_key_base: b0665be2cc638e85fe8291009ded82d8b8e22f4f25159408f1cd03cdbed697656febe08e6bf441f10a04b8f9a2e0e130fd877fe5ccdf57903ef27505711a23ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
